### ISSUE TITLE
Updates are not visible

### ISSUE THREAD

**Issue by edwardoid** [freecar/freecar-web#42]
When I'm opening freecar.am I can't see updated data(I see only 6 rows). Tried on Chrome/IE9. Cleaning all cache data _does_ not help.
Now I can see last updates only by using anonimizers.

**Comment by hmayaktigranyan** [comment]
screenshot plz

**Comment by edwardoid** [comment]
Chrome
![capture](https://f.cloud.github.com/assets/386374/855538/f25ac67c-f527-11e2-9e66-eb7fb1f2a8f0.PNG)

**Comment by hmayaktigranyan** [comment]
kam browser cache-a kam dns,mihat browser cache maqreq ete nuyna,uremn mihat "ping freecar.am"

**Comment by edwardoid** [comment]
Not working again.
Cleaning browser cache does not helped.
Ping output:

Pinging freecar.am [216.224.186.45] with 32 bytes of data:
Reply from 216.224.186.45: bytes=32 time=178ms TTL=42
Reply from 216.224.186.45: bytes=32 time=171ms TTL=42
Reply from 216.224.186.45: bytes=32 time=169ms TTL=42
Reply from 216.224.186.45: bytes=32 time=169ms TTL=42

Ping statistics for 216.224.186.45:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 169ms, Maximum = 178ms, Average = 171ms

**Comment by hmayaktigranyan** [comment]
DNS cacha,
Pinging freecar.am [192.30.164.231] with 32 bytes of data:
Reply from 192.30.164.231: bytes=32 time=169ms TTL=48
Reply from 192.30.164.231: bytes=32 time=170ms TTL=48
Reply from 192.30.164.231: bytes=32 time=170ms TTL=48
Reply from 192.30.164.231: bytes=32 time=169ms TTL=48

inch interneta?karam arajarkem uxxaki hosterum poxeq ip-n http://www.sevenforums.com/network-sharing/42517-how-set-etc-hosts-file-windows-7-a.html

avelacreq:
192.30.164.231 freecar.am
192.30.164.231 www.freecar.am
