### ISSUE TITLE
Page won't load on IE10

### ISSUE THREAD

**Issue by tigranpetrossian** [freecar/freecar-web#51]
Screenshot:
http://cl.ly/image/2f1y0t0m1C2k

**Comment by grigy** [comment]
Doh! This is a limitation of Parse. IE works only if the JavaScript is served from HTTPS.

Details here:
https://www.parse.com/questions/internet-explorer-and-the-javascript-sdk

I suggest to show a beautiful alert: "IE is not supported. Please use a better browser and link to chrome and firefox.
